const filterOptions = {
  type: ['all', 'movie', 'tv', 'ova', 'ona', 'special', 'music'],
  status: ['all', 'finished_airing', 'currently_airing', 'not_yet_aired'],
  rated: ['all', 'g', 'pg', 'pg-13', 'r', 'r+', 'rx'],
  score: [
    'all',
    'appalling',
    'horrible',
    'very_bad',
    'bad',
    'average',
    'fine',
    'good',
    'very_good',
    'great',
    'masterpiece',
  ],
  season: ['all', 'spring', 'summer', 'fall', 'winter'],
  language: ['all', 'sub', 'dub', 'sub_dub'],
  sort: [
    'default',
    'recently-added',
    'recently-updated',
    'score',
    'name-az',
    'released-date',
    'most-watched',
  ],
  genres: [
    'action',
    'adventure',
    'cars',
    'comedy',
    'dementia',
    'demons',
    'drama',
    'ecchi',
    'fantasy',
    'game',
    'harem',
    'historical',
    'horror',
    'isekai',
    'josei',
    'kids',
    'magic',
    'martial-arts',
    'mecha',
    'military',
    'music',
    'mystery',
    'parody',
    'police',
    'psychological',
    'romance',
    'samurai',
    'school',
    'sci-fi',
    'seinen',
    'shoujo',
    'shoujo-ai',
    'shounen',
    'shounen-ai',
    'slice-of-life',
    'space',
    'sports',
    'super-power',
    'supernatural',
    'thriller',
    'vampire',
    'yaoi',
    'yuri',
  ],
};

export const genreNames: Record<string, string> = {
  action: 'Action',
  adventure: 'Adventure',
  cars: 'Cars',
  comedy: 'Comedy',
  dementia: 'Dementia',
  demons: 'Demons',
  drama: 'Drama',
  ecchi: 'Ecchi',
  fantasy: 'Fantasy',
  game: 'Game',
  harem: 'Harem',
  historical: 'Historical',
  horror: 'Horror',
  isekai: 'Isekai',
  josei: 'Josei',
  kids: 'Kids',
  magic: 'Magic',
  'martial-arts': 'Martial Arts',
  mecha: 'Mecha',
  military: 'Military',
  music: 'Music',
  mystery: 'Mystery',
  parody: 'Parody',
  police: 'Police',
  psychological: 'Psychological',
  romance: 'Romance',
  samurai: 'Samurai',
  school: 'School',
  'sci-fi': 'Sci-Fi',
  seinen: 'Seinen',
  shoujo: 'Shoujo',
  'shoujo-ai': 'Shoujo Ai',
  shounen: 'Shounen',
  'shounen-ai': 'Shounen Ai',
  'slice-of-life': 'Slice of Life',
  space: 'Space',
  sports: 'Sports',
  'super-power': 'Super Power',
  supernatural: 'Supernatural',
  thriller: 'Thriller',
  vampire: 'Vampire',
  yaoi: 'Yaoi',
  yuri: 'Yuri',
};

export default filterOptions;
